# Copyright (C) 2026 Meltran, Inc
"""Shared helpers for the triplets-based examples.

triplets (https://pypi.org/project/triplets/) holds a CIM model as one
DataFrame of ``ID, KEY, VALUE, INSTANCE_ID`` rows and exports CIM RDF/XML from
it in the row order it holds, so the output is deterministic without a sort
step.  Install with ``pip install "triplets[validation,excel]"``.
"""
import datetime
import json
import uuid
from pathlib import Path

import pandas
import triplets  # noqa: F401  (registers pandas.read_RDF and the DataFrame export methods)
from triplets.export import export_to_cimxml
from triplets.tools import tableviews_to_triplets

REPO = Path(__file__).resolve().parents[2]
EMTIOP = REPO / "emtiop"
PROFILE_NS = "http://opensource.ieee.org/emtiop01p01#"
SERIALIZATIONS = ("552_ED2", "552_ED1", "plain")   # first one is the default


def load_rdf_map(serialization="552_ED2"):
    """The EMTIOP export schema generated by ``emtiop/build_rdf_map.py``: ``{"EMTIOP": {...}}``."""
    return json.loads((EMTIOP / f"emtiop_rdf_map_{serialization}.json").read_text())


def model_id(*parts):
    """Deterministic UUID for a model document, e.g. ``model_id(case["id"], "ic")``."""
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "/".join(parts))).upper()


def full_model(model_id, description, created, schema, authority="http://opensource.ieee.org/emtiop"):
    """One-row FullModel tableview (IEC 61970-552 header), or None when the schema has no header (plain)."""
    if "FullModel" not in schema["EMTIOP"]:
        return None
    if isinstance(created, (int, float)):
        created = datetime.datetime.fromtimestamp(created, datetime.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return pandas.DataFrame({"Model.created": [created], "Model.description": [description],
                             "Model.profile": [PROFILE_NS], "Model.modelingAuthoritySet": [authority]},
                            index=pandas.Index([model_id], name="ID"))


def to_triplets(tableviews, instance_id, header=None):
    """Wide per-class tables (index ``ID``, columns = ``Class.attribute``) -> triplets.

    Objects come out in dict order then row order, attributes in column order; the
    header, when given, goes first.
    """
    if header is not None:
        tableviews = {"FullModel": header, **tableviews}
    data = tableviews_to_triplets(tableviews)
    data["INSTANCE_ID"] = instance_id
    return data


def write_cimxml(data, schema, path):
    """Export one instance file; returns the bytes written.

    With a FullModel header the profile is resolved from Model.profile against the
    schema's ProfileMetadata; header-less data gets the EMTIOP section directly.
    """
    rdf_map = schema if (data["KEY"] == "Model.profile").any() else schema["EMTIOP"]
    content = export_to_cimxml(data, rdf_map=rdf_map, export_type="xml_per_instance",
                               export_to_memory=True)[0].getvalue()
    Path(path).write_bytes(content)
    return content
